@startuml
!theme sunlust
autonumber
skinparam Style awesome
skinparam SequenceMessageAlignment center

actor "Usuário" as User
participant "API Gateway" as Gateway
participant "Identity Access Manager Service" as IAM
queue "restaurant.user.created" as RestaurantUsuarioCriado
queue "restaurant.user.updated" as RestaurantUsuarioAlterado
queue "restaurant.user.deleted" as RestaurantUsuarioDelete

== Fluxo de Cadastro ==
User -> Gateway : POST /user (dados do usuário)
Gateway -> IAM : Roteia para Criação de Cliente
IAM -> IAM : Valida e Persiste Cliente no DB
IAM -->> Gateway : 201 Created
Gateway -->> User : Cadastro realizado com sucesso
IAM -> RestaurantUsuarioCriado : Publica evento 'pedido.usuario.criado'

== Fluxo de Alteração de Cadastro ==
User -> Gateway : PUT /user/{id} (dados do usuário)
Gateway -> IAM : Roteia para Criação de Cliente
IAM -> IAM : Valida e Persiste Cliente no DB
IAM -->> Gateway : 201 Created
Gateway -->> User : Alteração realizada com sucesso
IAM -> RestaurantUsuarioAlterado : Publica evento 'pedido.usuario.alterado'

== Fluxo de Exclusão de Cadastro ==
User -> Gateway : DELETE /user/{id} (dados do usuário)
Gateway -> IAM : Roteia para Criação de Cliente
IAM -> IAM : Valida e Persiste Cliente no DB
IAM -->> Gateway : 204 No Content
Gateway -->> User : Excluido com sucesso
IAM -> RestaurantUsuarioAlterado : Publica evento 'pedido.usuario.alterado'

== Fluxo de Autenticação ==
User -> Gateway : POST /auth/login (credenciais)
Gateway -> IAM : Roteia para Login
IAM -> IAM : Valida Credenciais
IAM -->> Gateway : 200 Autenticado com Sucesso
Gateway -->> User : JWT Token
@enduml